### PR TITLE
fix(mssql-driver): Fix group by clause for queries with dimensions and cumulative measures in MS SQL

### LINKED ISSUE #6525: Group by doesn't include dimensions for MS SQL when using a cumulative measure
**Describe the bug**
The MS SQL adapter leaves any dimensions present in the query off the SQL group by clause when an `overTimeSeriesSelect` is used to generate the query (for example, when using a `rollingWindow` for a measure).

**To Reproduce**
1. Set up a cube with a rollingWindow measure, a dimension and a `time` dimension.
2. Connect to an MS SQL database
3. Query the cube using the measure, the dimension and the time dimension with some granularity.
4. The query fails because the generated SQL doesn't include the dimension in the group by clause.

Seems to be introduced by this PR: https://github.com/cube-js/cube/pull/1169

**Expected behavior**
The query should succeed. For example, if you connect to a Postgresql database it will succeeed.

**Minimally reproducible Cube Schema**

```javascript
cube(`Orders`, {
  sql: `
  select * from orders
  `,
  measures: {
    weeklyCount: {
      sql: `id`,
        type: `count`,
        rollingWindow: {
          trailing: `7 day`,
          offset: `start`,
        },
    },
  },
  dimensions: {
    status: {
      sql: `status`,
      type: `string`,
    },

    createdAt: {
      sql: `created_at`,
      type: `time`
    },
  },
});
```

**Version:**
0.32.31

### PR DESCRIPTION
**Pull request by mfclarke-cnx**
Should resolve #6525

- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

I couldn't execute integration tests for MS SQL (I'm on an M1). Hopefully you folks are ok with the CI executing those after review?

Thanks

### CODE REVIEW

**Comment by mfclarke-cnx** [comment]
I've updated this after doing some real world testing. Now seems to be working fine for me.

I'd really appreciate a PR review, thank you!

**Comment by paveltiunov** [comment]
@mfclarke-cnx Thanks for contributing! Could you please add the test which runs SQL against MSSQL db either in schema-compiler, smoke E2E or driver test suite?

**Comment by mfclarke-cnx** [comment]
@paveltiunov updated!

Not sure why it's saying I'm trying to deploy to Vercel though? I just pushed new commits with test file changes.

**Comment by mfclarke-cnx** [comment]
@paveltiunov Is there anything you're waiting for me to do here?

**Comment by mfclarke-cnx** [comment]
Hi @paveltiunov just want to make sure this one doesn't get lost. We're starting to look at Cube Cloud as we get closer to scaling up, and without this fix in the official Cube, Cube Cloud isn't viable for us.

Please let me know what else I can do to get this fix merged. Thank you.

**Pull request merged**
