### PR TITLE
feat(duckdb-driver): Upgrade to Duckdb 1.1.1

### PR DESCRIPTION
**Pull request by benyaminsalimi**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Description of Changes Made**

upgrade duckdb to 1.1.1

### CODE REVIEW

**Comment by ovr** [comment]
Hello @benyaminsalimi,

Could you please rebase your PR and bump DuckDB to `1.1.2`?

Thanks

**Comment by taras** [comment]
https://registry.yarnpkg.com/duckdb/-/duckdb-1.1.3.tgz is available

**Comment by igorlukanin** [comment]
@benyaminsalimi Could you please update the PR?

**Comment by igorlukanin** [comment]
Closing this one as superseded by https://github.com/cube-js/cube/pull/9008

**Pull request closed without merging**
