### PR TITLE
feat(view): members inherit title attribute

### PR DESCRIPTION
**Pull request by CallumWalterWhite**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

#7475

**Description of Changes Made (if issue reference is not provided)**

Modified CubeSymbol.js to assign the resolved members' title.

### CODE REVIEW

**Comment by igorlukanin** [comment]
@CallumWalterWhite Thanks for contributing this!

I wonder if more [dimension](https://cube.dev/docs/reference/data-model/dimensions)/[measure](https://cube.dev/docs/reference/data-model/measures) attributes make sense to be inherited by respective view members:
- `description`
- `meta`
- `drill_members`
- `format`

WDYT @paveltiunov @CallumWalterWhite?

**Comment by paveltiunov** [comment]
@CallumWalterWhite Definitely makes sense to expose all meta fields as part of this change.

**Comment by CallumWalterWhite** [comment]
@igorlukanin @paveltiunov Cheers for the feedback!

I've expose all the meta fields from the given list - only ones missing were `format` & `drill_members`.

**Comment by CallumWalterWhite** [comment]
@igorlukanin @paveltiunov 
Any chance this PR could be reviewed again?

Thank you!!

**Comment by abdel-87** [comment]
Hi,
I do miss the inheritence of the “shown” attribute. Can that also be fixed please? @paveltiunov

**Pull request merged**
