### PR TITLE
fix(api-gateway): fixes an issue where queries t…

### PR DESCRIPTION
**Pull request by rdwoodring**
fix(api-gateway) fix(schema-compiler): fixes an issue where queries to get the total count of results were incorrectly applying sorting from the original query and also were getting default ordering applied when the query ordering was stripped out

**Check List**
- [ ] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

[#7446](https://github.com/cube-js/cube/issues/7446)

**Description of Changes Made (if issue reference is not provided)**

- updates api gateway to remove `order` field from queries that are getting a count of total results matching
- updates the base query's logic for defaulting `order` so that it does an early return and _does not_ default `order` if the query is getting the total (follows the same path as the logic doing an early return for preaggreation queries)

### CODE REVIEW

**Comment by paveltiunov** [comment]
@rdwoodring Thanks for contributing! We'd need E2E tests for that. You can put it in the Postgres smoke test.

**Comment by rdwoodring** [comment]
Any specific tests you'd like to see, @paveltiunov ? Just that queries with `totalQuery` return results without an error? Or can I actually test what query is being generated against the database to see that it does not have an order by?

Thanks

**Comment by paveltiunov** [comment]
@rdwoodring The later

**Comment by niravjprabtani** [comment]
Could we please get this PR reviewed ? I am facing issues in one of the project due to this and I had to execute multiple same queries just to get total number of records.

**Pull request merged**
