### PR TITLE
feat(duckdb-driver): Add support for installing and loading DuckDB Extensions.

### PR DESCRIPTION
**Pull request by ramalingamt**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [X] Docs have been added / updated if required

**Issue Reference this PR resolves**
#8737

**Description of Changes Made (if issue reference is not provided)**

### CODE REVIEW

**Comment by igorlukanin** [comment]
@ramalingamt Could you please resolve the conflict with the main branch?

**Comment by ramalingamt** [comment]
@igorlukanin - have pulled changes, merged and resolved the conflict in one file (env.ts).
Please check and let me know if anything is amiss.

**Comment by KSDaemon** [comment]
@ramalingamt Could you please also fix linter errors? (possibly with the help of `yarn run lint:fix`)

**Comment by KSDaemon** [comment]
@ramalingamt And if you don't mind — please sync with the latest master (it would be easy, and no conflicts, but there are some updates related to ci)

**Comment by KSDaemon** [comment]
Gentle pinging @ramalingamt

**Pull request merged**
