### PR TITLE
Add Codecov badge to README

### PR DESCRIPTION
**Pull request by thomasrockhu**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**
N/A

**Description of Changes Made (if issue reference is not provided)**
Tom from Codecov here. I thought I would go ahead and add the Codecov badge here in case it's useful!

### CODE REVIEW

**Comment by rpaik** [comment]
@igorlukanin can you help with the review?

**Review by hassankhan — COMMENTED** [review]
Just wondering if we should add the badge to all the package READMEs to be consistent?

/cc @keydunov

**Comment by igorlukanin** [comment]
@thomasrockhu Thank you! Codecov is great, though I think that we need to configure the coverage across our entire mono repo first, so the info shown on the badge makes sense. For that, community contributions are very much welcome.

**Comment by thomasrockhu** [comment]
@igorlukanin, would the ideal situation be the same badge added to all directories under `packages`?

**Comment by igorlukanin** [comment]
@thomasrockhu Yes, that would do a part of the job. We also need to configure the coverage for every package properly.

**Pull request closed without merging**
