### PR TITLE
Make  Cubestore metrics collector address configurable

### PR DESCRIPTION
**Pull request by fbalicchia**
Hi,
could you please review this pr. The capability that tried to add is the following describe in this [issue](https://github.com/cube-js/cube.js/issues/6314)

### CODE REVIEW

**Comment by paveltiunov** [comment]
@fbalicchia Overall looks good to me! Let's probably call it `CUBESTORE_METRICS_FORMAT` instead of `CUBESTORE_METRICS_COMPATIBILITY` and fix formatting issues.

**Comment by paveltiunov** [comment]
@fbalicchia Could you please rebase PR?

**Comment by fbalicchia** [comment]
@paveltiunov I merged the master on my branch. With rebasing, I'll need to rename branch. At the moment of writing merge and history seems clear. I'm wrong tell me thanks

**Comment by fbalicchia** [comment]
Close this issue in favor [issue](https://github.com/cube-js/cube/pull/6437) to understand why these tests failures

**Pull request closed without merging**
