### PR TITLE
feat(firebolt): Automatically start the engine after connection

### PR DESCRIPTION
**Pull request by stepansergeevitch**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

We've received a support ticket that a customer cannot connect to a stopped engine

**Description of Changes Made (if issue reference is not provided)**

- Added engine autostart to ensure we can connect to a stopped engine
- Added a verbose user message when testing connection fails

### CODE REVIEW

**Review by KSDaemon — APPROVED** [review]
👍🏻 Great! Thanks for the contribution!

**Comment by KSDaemon** [comment]
@stepansergeevitch Do unit tests work for you? I tried the `yarn run test` and saw that they failed. I wonder if your newly added test works. %)
```
 FAIL  dist/test/autostart.test.js (7.08 s)
  ● FireboltDriver autostart › calls engine start

    TypeError: Cannot read properties of undefined (reading 'includes')

      85 |
      86 |     const username = getEnv('dbUser', { dataSource });
    > 87 |     const auth = username.includes('@')
         |                           ^
      88 |       ? { username, password: getEnv('dbPass', { dataSource }) }
      89 |       : { client_id: username, client_secret: getEnv('dbPass', { dataSource }) };
      90 |

      at new FireboltDriver (src/FireboltDriver.ts:87:27)
      at test/autostart.test.ts:15:14
```

**Comment by stepansergeevitch** [comment]
> @stepansergeevitch Do unit tests work for you? I tried the `yarn run test` and saw that they failed. I wonder if your newly added test works. %)
> 
> ```
>  FAIL  dist/test/autostart.test.js (7.08 s)
>   ● FireboltDriver autostart › calls engine start
> 
>     TypeError: Cannot read properties of undefined (reading 'includes')
> 
>       85 |
>       86 |     const username = getEnv('dbUser', { dataSource });
>     > 87 |     const auth = username.includes('@')
>          |                           ^
>       88 |       ? { username, password: getEnv('dbPass', { dataSource }) }
>       89 |       : { client_id: username, client_secret: getEnv('dbPass', { dataSource }) };
>       90 |
> 
>       at new FireboltDriver (src/FireboltDriver.ts:87:27)
>       at test/autostart.test.ts:15:14
> ```

Hey @KSDaemon 
This test actually requires you to set the env variables for the driver.
Specifiсally `CUBEJS_DB_USER`,  `CUBEJS_DB_PASS`, `CUBEJS_DB_NAME`, `CUBEJS_FIREBOLT_ACCOUNT` and `CUBEJS_FIREBOLT_ENGINE_NAME`

**Comment by KSDaemon** [comment]
@stepansergeevitch Once again — thnx for the contribution! Merging! I'll setup CI integration tests later.

**Pull request merged**
