### PR TITLE
fix: Redis driver throws TypeError under high load

### PR DESCRIPTION
**Pull request by schneefux**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

N/A

**Description of Changes Made (if issue reference is not provided)**

Fixes "TypeError: result is not iterable at RedisQueueDriverConnection.retrieveForProcessing". The return value of `execAsync` is undefined if the redis transaction fails due to out of memory errors, see https://redis.io/docs/interact/transactions/#errors-inside-a-transaction. This is a regression of 101b85f0a2e5852a01b19ecd43d75736124664b9.

### CODE REVIEW

**Comment by igorlukanin** [comment]
Hi @schneefux 👋 I'll let @paveltiunov to review this one but, just FYI, Redis support is deprecated and is subject to be removed from Cube: https://cube.dev/docs/product/deployment#redis

**Comment by paveltiunov** [comment]
@schneefux Redis support is deprecated, and we do not accept any changes to this code base. Please consider moving to Cube Store.

**Comment by schneefux** [comment]
Since migrating to cubestore in early fall last year, I've had severe performance issues, the cube API servers and cubestore would randomly hang up. This was probably caused by a memory leak introduced in 0.34, see #7545.

I have been running the Redis store for multiple years without any issues so I'd prefer to use it as long as possible until cubestore is more stable.

**Comment by paveltiunov** [comment]
@schneefux Sorry to hear that! We didn't see anything like that in our production environments, so it might be configuration differences. We're open to merging any Cube Store fixes regarding OOM, and I believe this is the only way we have right now.

**Pull request closed without merging**
