### PR TITLE
Update @babel dependency version

### PR DESCRIPTION
**Pull request by anna-poz**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [ ] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**

The current version of @babel has a known vulnerability, https://github.com/advisories/GHSA-67hx-6x53-jw92

**Description of Changes Made (if issue reference is not provided)**

Update the version of @babel/traverse to 7.24, and also update the versions of other @babel packages to match.

### CODE REVIEW

**Comment by paveltiunov** [comment]
@anna-poz I guess it'd be quite a change. We can start with fixing the tests.

**Comment by anna-poz** [comment]
> @anna-poz I guess it'd be quite a change. We can start with fixing the tests.

Do you have some pointers on how to run the relevant tests locally? I am not familiar with your repo at all unfortunately.

**Comment by paveltiunov** [comment]
@anna-poz I believe https://github.com/cube-js/cube/blob/master/CONTRIBUTING.md would be a great starting point for it.

**Comment by anna-poz** [comment]
@paveltiunov I tried to follow the instructions, but when I run `yarn test` in the `packages/cubejs-schema-compiler` directory, I get errors like `Cannot find module '@cubejs-backend/shared'` (and there are a few more similar ones for other backend packages).

https://github.com/cube-js/cube/blob/master/CONTRIBUTING.md#testing-schema-compiler says that I just need to "have running Docker on your machine", but I am not sure what exactly that means. No matter whether I had something running with `docker run` or not, `yarn test` failed exactly the same way.

I also tried following https://github.com/cube-js/cube/blob/master/CONTRIBUTING.md#cube-server to `yarn link` the packages the test is complaining about, and that made no difference.

It looks like you are able to run tests on the PR in GitHub (https://github.com/cube-js/cube/actions/runs/8331740820/job/22907019108), but I cannot do that on my own unfortunately, and if I don't have the right commands to see the same errors locally, it's going to be impossible for me to fix the type errors.

I would really appreciate some help figuring out the exact commands to run so I can see the same errors, and get them all fixed.

**Comment by ovr** [comment]
I will close this PR in favor of https://github.com/cube-js/cube/pull/7875, which I opened earlier and already fixed issues with the building. I will merge it later, after solving an issue with yarn & workspace.

Thanks

**Pull request closed without merging**
