### PR TITLE
fix(jsonwebtoken) Package update to handle the dependabot alerts #6178

### PR DESCRIPTION
**Pull request by DhanushNehru**
**Check List**
- [x] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [x] Tests for the changes have been added if not covered yet
- [x] Docs have been added / updated if required

**Issue Reference this PR resolves**

 #6178

### CODE REVIEW

**Comment by DhanushNehru** [comment]
HI @paveltiunov can you please review this asap ?

**Comment by paveltiunov** [comment]
@DhanushNehru We'd need to fix all the tests here.

**Comment by DhanushNehru** [comment]
Hi @paveltiunov can you check now ?

**Comment by DhanushNehru** [comment]
Hi @paveltiunov can you check now , I could see the test cases passed with a green tick

**Comment by DhanushNehru** [comment]
Hi @paveltiunov can you check now ?

**Comment by DhanushNehru** [comment]
Hi @paveltiunov can you check now, all tests are fixed

**Comment by igorlukanin** [comment]
@DhanushNehru Please make sure this PR passes the tests. Currently, they fail:
image (53)

**Comment by DhanushNehru** [comment]
Hi @igorlukanin , looks like when the code is updated in the main cubejs repo, I need to sync it with my own forked repo each time when there is an update in the code

I just synced the code now, can you check it, as the tests have passed with a green tick. Let me know if I am missing something

Screenshot 2023-04-10 at 5 22 22 PM

**Comment by DhanushNehru** [comment]
HI @igorlukanin any updates on this ?

**Comment by DhanushNehru** [comment]
HI @igorlukanin  any updates on this ?

**Pull request closed without merging**
