### PR TITLE
feat(dbt_metrics): Filter tags support / Support for versions >= 1.3

### PR DESCRIPTION
**Pull request by dkucharc**
**Check List**
- [ ] Tests has been run in packages where changes made if available
- [x] Linter has been run for changed code
- [ ] Tests for the changes have been added if not covered yet
- [ ] Docs have been added / updated if required

**Issue Reference this PR resolves**
- #5591

**Description of Changes Made (if issue reference is not provided)**
In version `1.3` of `dbt` there were some breaking changes introduced to the logic responsible for generating the manifest. For more details, please check the corresponding [release notes](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.3#for-users-of-dbt-metrics). As a consequence, appropriate changes has to be made on the plugin side.

### CODE REVIEW

**Comment by paveltiunov** [comment]
@dkucharc Thanks for the contribution! Is there any chance you can add simple test here: 
https://github.com/cube-js/cube.js/blob/2975d84cd2a2d3bba3c31a7744ab5a5fb3789b6e/packages/cubejs-testing/birdbox-fixtures/postgresql/schema/Dbt.js
https://github.com/cube-js/cube.js/blob/e8c72d630eecd930a8fd36fc52f9b594a45d59c0/packages/cubejs-testing/test/abstract-test-case.ts

**Comment by dkucharc** [comment]
@paveltiunov In terms of modifying the existing tests, I have a few questions. Namely:
- Shall we keep the code/tests backward-compatible? In general, the old version of dbt metrics model is going to be replaced in v.1.4 onwards (more details can be found [here](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.3#for-users-of-dbt-metrics))
- Looking at the existing [test fixtures](https://github.com/cube-js/cube.js/tree/master/packages/cubejs-testing/birdbox-fixtures/postgresql/dbt-project), I think it would be beneficial to commit the entire dbt project as it definitely helps keeping `manifest.json` updated properly. At this stage we have two choices. Namely: 1) share/commit the `dbt_project` (based on which the initial test fixtures were generated) and get `manifest.json` recreated 2) introduce a new `dbt_project` with all relevant files.

**Comment by dkucharc** [comment]
@paveltiunov I would appreciate if you could share your thoughts regarding possible way of updating relevant tests here.

**Comment by paveltiunov** [comment]
@dkucharc Ideally, we support both versions in a dynamic way if possible. You can create a new test and new test project to test the new format.

**Comment by keydunov** [comment]
Due to the [change in direction](https://docs.getdbt.com/blog/deprecating-dbt-metrics) at dbt, we are deprecating `@cubejs-backend/dbt-schema-extension`. When a new dbt metrics package becomes available, we will update and reintroduce our integration.

**Pull request closed without merging**
