### PR TITLE
docs: Update join relationship types

### PR DESCRIPTION
**Pull request by igorlukanin**

### CODE REVIEW

**Comment by keydunov** [comment]
@igorlukanin Do we have a message here that old relationship names are still valid?

**Comment by igorlukanin** [comment]
@keydunov Yep, [here it is](https://github.com/cube-js/cube/pull/6476/files#diff-3d51b22a3229ea730c1359ee2178da43d55b50ed6d825d13828d000d111ec03bR118-R124):
Screenshot 2023-04-21 at 21 55 38

**Review by hassankhan — APPROVED** [review]
Love it, great job @igorlukanin 💯

**Comment by keydunov** [comment]
> @keydunov Yep, [here it is](https://github.com/cube-js/cube/pull/6476/files#diff-3d51b22a3229ea730c1359ee2178da43d55b50ed6d825d13828d000d111ec03bR118-R124):
> 
> Screenshot 2023-04-21 at 21 55 38

Thanks @igorlukanin! Can we add this message to working with joins page too?

**Comment by keydunov** [comment]
Ok, let's merge without 2nd warning. I think it should be enough, but if we see questions in the community (Slack & Github), we'd need to add more warning messages.

**Review by keydunov — APPROVED** [review]

**Pull request merged**
